version: '3.7'

services:
  db:
    image: postgres:alpine
    restart: always
    container_name: dbt2
    environment:
      - POSTGRES_USER=${RVS_DB_USER}
      - POSTGRES_PASSWORD=${RVS_DB_USER}
      - POSTGRES_DB=${RVS_DB_NAME}
    ports:
      - ${RVS_DB_PORT}:${RVS_DB_PORT}

  server:
    build: web
    container_name: webt2
    environment:
      - RVS_DB_NAME=${RVS_DB_NAME}
      - RVS_DB_PORT=${RVS_DB_PORT}
      - RVS_DB_HOST=${RVS_DB_HOST}
      - RVS_DB_USER=${RVS_DB_USER}
      - RVS_DB_PASS=${RVS_DB_USER}
      - RVS_APP_PORT=${RVS_APP_PORT}
      - RVS_APP_IP=${RVS_APP_IP}
    command: python manage.py runserver 0.0.0.0:${RVS_APP_PORT}
    ports:
      - ${RVS_APP_PORT}:${RVS_APP_PORT}
    depends_on:
      - db
